export function uniq(a: any, param: any): any;
export const emptyAddress: "0x0000000000000000000000000000000000000000";
export function getEnsStartBlock(networkId: any): 0 | 3327417 | 25409;
export function checkLabels(...labelHashes: any[]): any[];
export function mergeLabels(labels1: any, labels2: any): any;
export function validateName(name: any): any;
export function parseSearchTerm(term: any, validTld: any): "short" | "address" | "invalid" | "search" | "supported" | "unsupported" | "tld";
export function isLabelValid(name: any): boolean;
import { labelhash } from "./labelhash";
import { isEncodedLabelhash } from "./labelhash";
import { isDecrypted } from "./labelhash";
import { decodeLabelhash } from "./labelhash";
import { encodeLabelhash } from "./labelhash";
import { namehash } from "./namehash";
import { encodeContenthash } from "./contents";
import { decodeContenthash } from "./contents";
import { isValidContenthash } from "./contents";
export { labelhash, isEncodedLabelhash, isDecrypted, decodeLabelhash, encodeLabelhash, namehash, encodeContenthash, decodeContenthash, isValidContenthash };
